version: "3.3"

services:
  nestar-api: 
    container_name: nestar-api
    restart: always
    image: node:20.10.0
    ports:
      - "4001:3005"
    volumes:
      - ./:/usr/src/nestar
    working_dir: /usr/src/nestar
    networks:
      - monorepo-network
    env_file:
      - .env
    command: bash -c "npm install && npx nest build nestar-api && npm run start:prod"

  nestar-batch: 
    container_name: nestar-batch
    restart: always
    image: node:20.10.0
    ports:
      - "4002:3005"
    volumes:
      - ./:/usr/src/nestar
    working_dir: /usr/src/nestar
    networks:
      - monorepo-network
    env_file:
      - .env
    command: bash -c "npm install && npx nest build nestar-batch && npm run start:prod:batch"

networks:
  monorepo-network:
    driver: bridge
    
# Port mapping:
# nestar-api: localhost:4001 => container:3005
# nestar-batch: localhost:4002 => container:3005